version: '3.1'

services:
  db:
    image: postgres12
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account-service
    ports:
    - "5432:5432"